name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build&Push
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[skip build]')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get repository info
        uses: gacts/github-slug@v1
        id: slug
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/koochdocker:client-${{ steps.slug.outputs.commit-hash-short }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[skip ci]') && !contains(github.event.commits[0].message, '[skip deploy]')"
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v2

    - 
      name: Install SSH
      run: sudo apt-get update && sudo apt-get install -y openssh-client
    
    - 
      name: Get repository info
      uses: gacts/github-slug@v1
      id: slug

    - 
      name: Update Docker Compose
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o "StrictHostKeyChecking no" -tt root@37.27.17.192 "sed -i 's|${{ secrets.DOCKERHUB_USERNAME }}/koochdocker:client-.*|${{ secrets.DOCKERHUB_USERNAME }}/koochdocker:client-${{ steps.slug.outputs.commit-hash-short }}|g' kooch/docker-compose.yml && cd kooch && docker compose up -d"